version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: asset_price_db
    environment:
      POSTGRES_DB: assetpricedb
      POSTGRES_USER: assetuser
      POSTGRES_PASSWORD: assetpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/ddl:/docker-entrypoint-initdb.d
      - ./db/conf/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U assetuser -d assetpricedb"]
      interval: 10s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: asset_price_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@assetpricedb.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data: 